### ISSUE TITLE
Parameter to omit field from output

### ISSUE THREAD

**Issue by jrdnull** [Teamwork/kommentaar#57] opened 2019-01-08 14:09 UTC
Is there a way I can omit a field from the output, e.g:

```
type paginate struct {
    // Page to retrieve {required}.
    Page int

    // Number of results in a single page {range: 20-100, default: 20}.
    PageSize int

    // Sorting order {enum: asc desc} {default: asc}.
    Order int

    // Only fetch results updated since this time {date-time}.
    UpdatedSince time.Time

    Internal bool // {omit}
}
```

`{-}` or `{omit}` ? 

I could use the json tag, `json:"-"` but I would like it in the json, I just don't want it appearing in the docs as its not really needed and adds a lot of extra fields.

**Comment by Carpetsmoker** [comment] 2019-01-08 15:04
No, there is no way right now. Haven't needed it yet. Should be easy to add if it's needed.

Also, dupe of: #47

**Closed** 2019-01-08 15:04 UTC

**Comment by Carpetsmoker** [comment] 2019-01-09 03:01
Actually not exact dupe, as the other issue is about hiding *parts* of the docs, while this is about omitting a field completely. Either way, I made a PR: #58
